name: Release
on: push

permissions:
  contents: write
  packages: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: lts/*
      - name: Install dependencies
        run: yarn
      - name: Boot up integration test environment
        run: cd infrastructure && docker compose -f docker-compose.yaml up -d --wait
      - name: Run Unit-Tests
        run: cd projects/lend-stats-service && yarn test:cov
      - name: Run Integration Tests
        run: cd projects/lend-stats-service && yarn test:e2e
      - name: Build Project
        run: cd projects/lend-stats-service && yarn build

      # TODO: Deployment